# Generated by Django 5.2.4 on 2025-09-29 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('grade_level', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_type',
            field=models.CharField(choices=[('student', 'Öğrenci'), ('teacher', 'Öğretmen'), ('admin', 'Yönetici'), ('parent', 'Veli')], db_index=True, default='student', help_text='Bu kullanıcı için temel profil tipi.', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ünvan')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Birim')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Okul Numarası')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.classroom', verbose_name='Sınıfı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yakınlık Notu')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='accounts.studentprofile', verbose_name='Çocukları / Öğrencileri')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(max_length=100, verbose_name='Branş')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Okul Dahili / Ofis Telefonu')),
                ('classrooms', models.ManyToManyField(blank=True, related_name='teachers', to='accounts.classroom', verbose_name='Derse Girdiği Sınıflar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='advisor_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_students', to='accounts.teacherprofile', verbose_name='Sınıf Danışmanı'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
