# Generated by Django 5.2.4 on 2025-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_advisor',
            field=models.BooleanField(default=False, help_text='Koçluk ödevi atama yetkisi olan öğretmen.', verbose_name='Rehber Öğretmen mi?'),
        ),
    ]
