# Generated by Django 5.2.4 on 2025-10-24 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('session_count', models.PositiveSmallIntegerField(default=2)),
                ('booklet_types', models.CharField(default='A/B', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(blank=True, default='', max_length=10)),
                ('student_no', models.CharField(blank=True, default='', max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('classroom', models.CharField(blank=True, default='', max_length=5)),
                ('gender', models.CharField(blank=True, default='', max_length=1)),
                ('session', models.CharField(blank=True, default='', max_length=2)),
                ('booklet_type', models.CharField(blank=True, default='A', max_length=1)),
                ('turkish_correct', models.FloatField(default=0)),
                ('turkish_wrong', models.FloatField(default=0)),
                ('turkish_net', models.FloatField(default=0)),
                ('history_correct', models.FloatField(default=0)),
                ('history_wrong', models.FloatField(default=0)),
                ('history_net', models.FloatField(default=0)),
                ('religion_correct', models.FloatField(default=0)),
                ('religion_wrong', models.FloatField(default=0)),
                ('religion_net', models.FloatField(default=0)),
                ('english_correct', models.FloatField(default=0)),
                ('english_wrong', models.FloatField(default=0)),
                ('english_net', models.FloatField(default=0)),
                ('math_correct', models.FloatField(default=0)),
                ('math_wrong', models.FloatField(default=0)),
                ('math_net', models.FloatField(default=0)),
                ('science_correct', models.FloatField(default=0)),
                ('science_wrong', models.FloatField(default=0)),
                ('science_net', models.FloatField(default=0)),
                ('total_correct', models.FloatField(default=0)),
                ('total_wrong', models.FloatField(default=0)),
                ('total_net', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('raw_line', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pdf_okuma.examset')),
            ],
        ),
        migrations.CreateModel(
            name='ExamKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booklet_type', models.CharField(default='A', max_length=1)),
                ('turkish', models.CharField(default='', max_length=20)),
                ('history', models.CharField(default='', max_length=10)),
                ('religion', models.CharField(default='', max_length=10)),
                ('english', models.CharField(default='', max_length=10)),
                ('math', models.CharField(default='', max_length=20)),
                ('science', models.CharField(default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='pdf_okuma.examset')),
            ],
            options={
                'unique_together': {('exam_set', 'booklet_type')},
            },
        ),
    ]
