# Generated by Django 5.2.4 on 2025-10-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_okuma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='booklet_type',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='school_code',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='session',
        ),
    ]
