# Generated by Django 5.2.4 on 2025-08-05 09:47

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('background_color', models.CharField(default='#007bff', max_length=20)),
                ('border_color', models.CharField(default='#0056b3', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okul_kodu', models.CharField(default='', max_length=10)),
                ('ogrenci_no', models.CharField(default='', max_length=10)),
                ('ad', models.CharField(default='', max_length=50)),
                ('soyad', models.CharField(default='', max_length=50)),
                ('sinif', models.CharField(default='', max_length=5)),
                ('cinsiyet', models.CharField(default='', max_length=1)),
                ('oturum', models.IntegerField(default=0)),
                ('kitapcik_turu', models.CharField(default='', max_length=1)),
                ('turkce', models.CharField(default='', max_length=20)),
                ('inkilap', models.CharField(default='', max_length=10)),
                ('din', models.CharField(default='', max_length=10)),
                ('ingilizce', models.CharField(default='', max_length=10)),
                ('matematik', models.CharField(default='', max_length=20)),
                ('fen', models.CharField(default='', max_length=20)),
                ('full_raw_line', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DersProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.CharField(choices=[('Pazartesi', 'Pazartesi'), ('Salı', 'Salı'), ('Çarşamba', 'Çarşamba'), ('Perşembe', 'Perşembe'), ('Cuma', 'Cuma'), ('Cumartesi', 'Cumartesi'), ('Pazar', 'Pazar')], default='Pazartesi', max_length=10)),
                ('Baslangic_saat', models.CharField(default='09:00', max_length=20)),
                ('Bitis_saat', models.CharField(default='09:40', max_length=20)),
                ('ders_kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categoryclass')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('status', models.IntegerField(default=1)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.city')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categoryimage')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('status', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categorytext')),
            ],
        ),
    ]
