# Generated by Django 5.2.4 on 2025-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='oturum',
            field=models.CharField(default=''),
        ),
    ]
