# Generated by Django 5.2.4 on 2025-08-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_studentresult_oturum'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='net',
            field=models.FloatField(default=0),
        ),
    ]
