# Generated by Django 5.2.4 on 2025-08-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studentresult_net'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okul_no', models.CharField(max_length=20)),
                ('ogrenci_no', models.CharField(max_length=20)),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('tc', models.CharField(blank=True, default='', max_length=20)),
                ('sinif', models.CharField(max_length=10)),
                ('cinsiyet', models.CharField(choices=[('Kız', 'Kız'), ('Erkek', 'Erkek')], max_length=10)),
                ('oturum', models.PositiveSmallIntegerField()),
                ('kitapcik', models.CharField(max_length=2)),
                ('cevaplar', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['okul_no'], name='base_studen_okul_no_52b99f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['ogrenci_no'], name='base_studen_ogrenci_116a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['sinif'], name='base_studen_sinif_9a4dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['cinsiyet'], name='base_studen_cinsiye_0821d3_idx'),
        ),
    ]
