# Generated by Django 5.2.4 on 2025-08-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_studentanswer_delete_studentresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okul_kodu', models.CharField(default='', max_length=10)),
                ('ogrenci_no', models.CharField(default='', max_length=10)),
                ('ad', models.CharField(default='', max_length=50)),
                ('soyad', models.CharField(default='', max_length=50)),
                ('sinif', models.CharField(default='', max_length=5)),
                ('cinsiyet', models.CharField(default='', max_length=1)),
                ('oturum', models.CharField(default='')),
                ('kitapcik_turu', models.CharField(default='', max_length=1)),
                ('turkce', models.CharField(default='', max_length=20)),
                ('inkilap', models.CharField(default='', max_length=10)),
                ('din', models.CharField(default='', max_length=10)),
                ('ingilizce', models.CharField(default='', max_length=10)),
                ('matematik', models.CharField(default='', max_length=20)),
                ('fen', models.CharField(default='', max_length=20)),
                ('full_raw_line', models.TextField()),
                ('net', models.FloatField(default=0)),
            ],
        ),
    ]
