# Generated by Django 5.2.4 on 2025-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='full_raw_line',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='oturum',
            field=models.CharField(default='', max_length=2),
        ),
    ]
