# Generated by Django 5.2.4 on 2025-08-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_studentresult_full_raw_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenemeSinavi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(help_text='Deneme sınavının adı', max_length=100)),
                ('aciklama', models.TextField(blank=True, help_text='İsteğe bağlı açıklama', null=True)),
                ('tarih', models.DateTimeField(help_text='Deneme sınavı tarihi')),
                ('oturum_sayisi', models.PositiveSmallIntegerField(default=1, help_text='Deneme sınavının oturum sayısı')),
                ('kitapcik_turleri', models.CharField(blank=True, help_text='Kitapçık türleri (örn: A/B/C)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentresult',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='deneme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='deneme_sinavi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='base.denemesinavi'),
        ),
    ]
