# Generated by Django 5.2.4 on 2025-08-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_denemesinavi_studentresult_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitapcik_turu', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('turkce', models.CharField(help_text='Türkçe cevapları (20 karakter)', max_length=20)),
                ('inkilap', models.CharField(help_text='İnkılap/Tarih cevapları (10 karakter)', max_length=10)),
                ('din', models.CharField(help_text='Din cevapları (10 karakter)', max_length=10)),
                ('ingilizce', models.CharField(help_text='İngilizce cevapları (10 karakter)', max_length=10)),
                ('matematik', models.CharField(help_text='Matematik cevapları (20 karakter)', max_length=20)),
                ('fen', models.CharField(help_text='Fen cevapları (20 karakter)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('kitapcik_turu',)},
            },
        ),
    ]
