# Generated by Django 5.2.4 on 2025-08-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_answerkey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='denemesinavi',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='answerkey',
            name='deneme_sinavi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cevap_anahtarlari', to='base.denemesinavi'),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='din',
            field=models.CharField(default='', help_text='Din cevapları (10 karakter)', max_length=10),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='fen',
            field=models.CharField(default='', help_text='Fen cevapları (20 karakter)', max_length=20),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='ingilizce',
            field=models.CharField(default='', help_text='İngilizce cevapları (10 karakter)', max_length=10),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='inkilap',
            field=models.CharField(default='', help_text='İnkılap/Tarih cevapları (10 karakter)', max_length=10),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='kitapcik_turu',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='matematik',
            field=models.CharField(default='', help_text='Matematik cevapları (20 karakter)', max_length=20),
        ),
        migrations.AlterField(
            model_name='answerkey',
            name='turkce',
            field=models.CharField(default='', help_text='Türkçe cevapları (20 karakter)', max_length=20),
        ),
        migrations.AlterField(
            model_name='denemesinavi',
            name='kitapcik_turleri',
            field=models.CharField(blank=True, default='A/B', help_text='Kitapçık türleri (örn: A/B/C)', max_length=50),
        ),
        migrations.AlterField(
            model_name='denemesinavi',
            name='oturum_sayisi',
            field=models.PositiveSmallIntegerField(default=2, help_text='Deneme sınavının oturum sayısı'),
        ),
        migrations.AlterField(
            model_name='denemesinavi',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, help_text='Deneme sınavı tarihi'),
        ),
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together={('deneme_sinavi', 'kitapcik_turu')},
        ),
    ]
