# Generated by Django 5.2.4 on 2025-10-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_address_name_alter_categoryclass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='ogrenci_no',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
