# Generated by Django 5.2.4 on 2025-10-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_studentresult_ogrenci_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='ogrenci_no',
            field=models.CharField(default='', max_length=10),
        ),
    ]
