# Generated by Django 5.2.4 on 2025-09-30 03:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Ders Adı')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Konu Adı')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konular', to='coach.ders', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['ders__ad', 'ad'],
                'unique_together': {('ders', 'ad')},
            },
        ),
        migrations.CreateModel(
            name='OgrenciDurumKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('hedef_soru', models.PositiveIntegerField(default=0, verbose_name='Hedef Soru')),
                ('kitap_okuma', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kitap Okuma')),
                ('veli_onayi', models.BooleanField(default=False, verbose_name='Veli Onayı')),
                ('pd_onayi', models.BooleanField(default=False, verbose_name='Psk. Dan. Onayı')),
                ('haftanin_sozu', models.TextField(blank=True, null=True, verbose_name='Haftanın Sözü')),
                ('calisilacak_konular', models.TextField(blank=True, null=True, verbose_name='Çalışılacak Konular')),
                ('oz_degerlendirme', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Kendini Değerlendirme (0-10)')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durum_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Öğrenci Durum Kaydı',
                'verbose_name_plural': 'Öğrenci Durum Kayıtları',
                'ordering': ('-tarih', '-olusturulma'),
                'unique_together': {('ogrenci', 'tarih')},
            },
        ),
        migrations.CreateModel(
            name='DersSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru', models.PositiveIntegerField(default=0, verbose_name='Doğru')),
                ('yanlis', models.PositiveIntegerField(default=0, verbose_name='Yanlış')),
                ('bos', models.PositiveIntegerField(default=0, verbose_name='Boş')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.ders', verbose_name='Ders')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.konu', verbose_name='Konu')),
                ('kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_sonuclari', to='coach.ogrencidurumkaydi', verbose_name='Durum Kaydı')),
            ],
            options={
                'verbose_name': 'Ders Sonucu',
                'verbose_name_plural': 'Ders Sonuçları',
                'ordering': ['ders__ad', 'konu__ad'],
                'unique_together': {('kayit', 'ders', 'konu')},
            },
        ),
    ]
