# Generated by Django 5.2.4 on 2025-10-06 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DersPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sınıf')),
                ('hedef_soru', models.PositiveIntegerField(default=0, verbose_name='Hedef Soru Sayısı')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.ders', verbose_name='Ders')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.konu', verbose_name='Konu')),
                ('ogrenciler', models.ManyToManyField(blank=True, related_name='ders_planlari', to=settings.AUTH_USER_MODEL, verbose_name='Öğrenciler')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturdugu_planlar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan (Rehberlik Hocası)')),
            ],
            options={
                'verbose_name': 'Ders Planı',
                'verbose_name_plural': 'Ders Planları',
                'ordering': ('-tarih',),
            },
        ),
    ]
