# Generated by Django 5.2.4 on 2025-11-22 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_teacherprofile_is_advisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, help_text="Boş bırakılırsa otomatik olarak 'İsteğe bağlı konu' atanır.", max_length=255, null=True)),
                ('target_question_count', models.PositiveIntegerField()),
                ('target_type', models.CharField(choices=[('grade', 'Seviye (tüm 8. sınıflar gibi)'), ('classroom', 'Belirli sınıf'), ('students', 'Belirli öğrenciler'), ('all', 'Tüm öğrenciler')], max_length=20)),
                ('grade_level', models.IntegerField(blank=True, help_text='Seviye hedeflemesi için (ör: 8)', null=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classroom')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to='accounts.teacherprofile')),
                ('students', models.ManyToManyField(blank=True, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_count', models.IntegerField(default=0)),
                ('wrong_count', models.IntegerField(default=0)),
                ('blank_count', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='coaching_v2.coachingassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_statuses', to='accounts.studentprofile')),
            ],
        ),
    ]
