# Generated by Django 5.2.4 on 2025-11-26 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teacherprofile_is_advisor'),
        ('coaching_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.teacherprofile'),
        ),
    ]
