# Generated by Django 5.2.4 on 2025-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'English')], max_length=10, verbose_name='Dil')),
                ('active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Soru-Cevap',
                'verbose_name_plural': 'Soru-Cevaplar',
            },
        ),
    ]
