# Generated by Django 5.2.4 on 2025-10-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
    ]
