# Generated by Django 5.2.4 on 2025-11-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
